server:
  port: 8763
spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
  application:
    name: resmanage
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/data_manage?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
#spring:
#  profiles:
#    active: dev

